name: Terraform CI

on:
  push:
    branches:
      - main
      - feature/newfeaturebranch

  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ./enviroment/preprod
        run: terraform init

      - name: Terraform Format Check
        working-directory: ./enviroment/preprod
        run: terraform fmt -check

      - name: Terraform Validate
        working-directory: ./enviroment/preprod
        run: terraform validate

      - name: Terraform Plan
        working-directory: ./enviroment/preprod
        run: terraform plan